override languages in environment when running commands
chef-partners/redhat-subscription-manager-cookbook pull request #33
Opened 2017-10-24 15:19 UTC by kleini

Fix for https://github.com/chef-partners/redhat-subscription-manager-cookbook/issues/32

2017-10-30 17:00 UTC, jjasghar requested changes

2017-10-30 17:00 UTC, jjasghar commented on libraries/helpers.rb
> +      cmd = Mixlib::ShellOut.new('subscription-manager status', env: { LANG: 'en_US' })
If possible it would be nice to have `en_US` as an attribute or something so if at some point we needed to override it we could.

2017-10-30 17:00 UTC, jjasghar commented on metadata.rb
> +version '0.6.1'
Please remove this, I'll take care of the version numbers.

2017-10-30 17:00 UTC, jjasghar commented on CHANGELOG.md
> +## [v0.6.1](https://github.com/chef-partners/redhat-subscription-manager-cookbook/tree/v0.6.1)
Thanks, but i use an automated changelog generator, so you can remove this.

2017-11-15 12:01 UTC, kleini commented
@jjasghar I fixed your requested changes. Please review.

2017-11-15 13:08 UTC, jjasghar commented
Please sign your commit via the DCO. Company policy won’t let me merge this unless you do.

2017-11-15 19:12 UTC, kleini commented
Signed.

2017-11-15 22:15 UTC, merged